<a href="https://colab.research.google.com/github/mseongkim/Colab-Test/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
x = torch.tensor([1,2,3])
x

tensor([1, 2, 3])

In [4]:
y = torch.tensor([
    [1,2,3],
    [2,3,4],
    [0,0,0]
    ], dtype=torch.float)
y

tensor([[1., 2., 3.],
        [2., 3., 4.],
        [0., 0., 0.]])

In [5]:
torch.ones(1,2, dtype=torch.int)

tensor([[1, 1]], dtype=torch.int32)

In [6]:
torch.zeros(5,3,2, dtype=torch.float)

tensor([[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]])

In [7]:
z = torch.rand(3,4,2, dtype=torch.float)
z

tensor([[[0.0718, 0.4139],
         [0.4853, 0.5117],
         [0.3761, 0.7033],
         [0.0359, 0.7815]],

        [[0.1500, 0.9038],
         [0.5008, 0.1972],
         [0.6446, 0.9367],
         [0.0259, 0.1630]],

        [[0.3567, 0.7623],
         [0.4413, 0.0644],
         [0.5919, 0.6529],
         [0.4273, 0.4087]]])

In [10]:
print(y)
y[0]

tensor([[1., 2., 3.],
        [2., 3., 4.],
        [0., 0., 0.]])


tensor([1., 2., 3.])

In [11]:
y[:,1]

tensor([2., 3., 0.])

In [12]:
z

tensor([[[0.0718, 0.4139],
         [0.4853, 0.5117],
         [0.3761, 0.7033],
         [0.0359, 0.7815]],

        [[0.1500, 0.9038],
         [0.5008, 0.1972],
         [0.6446, 0.9367],
         [0.0259, 0.1630]],

        [[0.3567, 0.7623],
         [0.4413, 0.0644],
         [0.5919, 0.6529],
         [0.4273, 0.4087]]])

In [13]:
z[2, :, 0]

tensor([0.3567, 0.4413, 0.5919, 0.4273])

In [15]:
y.size()

torch.Size([3, 3])

In [16]:
y.size()[0]

3